name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installer Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install && npm test

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Installer Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible
      - name: Déploiement
        run: |
          if [[ "${GITHUB_REF##*/}" == "dev" ]]; then
            ansible-playbook -i ansible/inventory/dev.ini ansible/playbooks/deploy-dev.yml
          else
            ansible-playbook -i ansible/inventory/prod.ini ansible/playbooks/deploy-prod.yml
          fi
